version: "2.1"

###### HOST MOUNTS ######
# NFS Mount Media to Host /media
# NFS Mount Data to Host /home

########################### EXTENSION FIELDS
x-environment: &default-tz-puid-pgid
  TZ: TZ=America/Chicago
  PUID: PUID=1000
  PGID: PGID=1000

x-common-keys: &common-keys
  environment:
    <<: *default-tz-puid-pgid
  restart: unless-stopped
########################### EXTENSION FIELDS

services:

  prowlarr:
    <<: *common-keys # See EXTENSION FIELDS
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    volumes:
      - /home/docker/prowlarr:/config
    ports:
      - 9696:9696

  radarr:
    <<: *common-keys # See EXTENSION FIELDS
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - /home/docker/radarr:/config
      - /media/movies:/movies #optional
      - /media/downloads:/downloads #optional
    ports:
      - 7878:7878

  sonarr:
    <<: *common-keys # See EXTENSION FIELDS
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - /home/docker/sonarr:/config
      - /media/tvseries:/tv #optional
      - /media/downloads:/downloads #optional
    ports:
      - 8989:8989

  lidarr:
    <<: *common-keys # See EXTENSION FIELDS
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    volumes:
      - /home/docker/lidarr:/config
      - /media/music:/music #optional
      - /media/downloads:/downloads #optional
    ports:
      - 8686:8686

  readarr:
    <<: *common-keys # See EXTENSION FIELDS
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    volumes:
      - /home/docker/readarr:/config
      - /media/books:/books #optional
      - /media/downloads:/downloads #optional
    ports:
      - 8787:8787
